package models

import "time"

// BillSequence holds the running book/receipt counters for one (store,
// type) pair. Numbering is generated by atomically updating this row inside
// the same transaction that creates a bill — see bill_module.Repository.
// CreateBill.
//
// A book holds at most MaxReceiptNoPerBook receipts before rolling over to
// the next book, and both counters reset to book 1 / receipt 1 at the start
// of every calendar year (tracked by comparing UpdatedAt's year against the
// current year) — the same rule the app used before this table existed,
// just scoped per (store, type) instead of per store.
type BillSequence struct {
	StoreID int    `json:"storeId" gorm:"column:store_id;primaryKey;not null;"`
	Store   *Store `json:"store,omitempty" gorm:"foreignKey:StoreID;references:ID;constraint:OnUpdate:CASCADE,OnDelete:RESTRICT;"`

	// Type is 'receipt' or 'payment' (CHECK) — see BillTypeReceipt/BillTypePayment.
	Type string `json:"type" gorm:"column:type;primaryKey;size:20;not null;"`

	LastBookNo    int `json:"lastBookNo" gorm:"column:last_book_no;not null;default:0;"`
	LastReceiptNo int `json:"lastReceiptNo" gorm:"column:last_receipt_no;not null;default:0;"`

	UpdatedAt time.Time `json:"updatedAt" gorm:"column:updated_at;default:CURRENT_TIMESTAMP;not null;"`
}
