definitions:
  exception.ErrorResponse:
    properties:
      code:
        type: string
      errors:
        items:
          $ref: '#/definitions/exception.ParameterError'
        type: array
      message:
        type: string
    type: object
  exception.ParameterError:
    properties:
      field:
        type: string
      tag:
        type: string
      value:
        type: string
    type: object
  http_response.OkResponse:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  paginator.Pagination:
    properties:
      attributes:
        additionalProperties: true
        type: object
      data: {}
      limit:
        type: integer
      orderBy:
        type: string
      page:
        type: integer
      sort:
        type: string
      totalPages:
        type: integer
      totalRows:
        type: integer
    type: object
  responses.GetProfileResponse:
    properties:
      createdAt:
        description: Timestamp & Audit fields
        type: string
      email:
        type: string
      firstName:
        type: string
      id:
        type: integer
      lastName:
        type: string
      role:
        allOf:
        - $ref: '#/definitions/responses.GetProfileRoleResponse'
        description: Relations
      updatedAt:
        type: string
    type: object
  responses.GetProfileRoleGroupRoleResponse:
    properties:
      code:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  responses.GetProfileRoleMenuResponse:
    properties:
      description:
        type: string
      icon:
        type: string
      id:
        type: integer
      isActive:
        type: boolean
      isFeature:
        type: boolean
      keyName:
        type: string
      label:
        type: string
      mode:
        type: string
      name:
        type: string
      permissions:
        items:
          $ref: '#/definitions/responses.GetProfileRolePermissionResponse'
        type: array
      subMenus:
        description: Relations
        items:
          $ref: '#/definitions/responses.GetProfileRoleMenuResponse'
        type: array
      urlPath:
        type: string
    type: object
  responses.GetProfileRolePermissionResponse:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  responses.GetProfileRoleResponse:
    properties:
      description:
        type: string
      id:
        type: integer
      label:
        type: string
      menus:
        items:
          $ref: '#/definitions/responses.GetProfileRoleMenuResponse'
        type: array
      name:
        type: string
      permissions:
        items:
          $ref: '#/definitions/responses.GetProfileRolePermissionResponse'
        type: array
      roleGroup:
        allOf:
        - $ref: '#/definitions/responses.GetProfileRoleGroupRoleResponse'
        description: Relations
    type: object
  responses.GetUserByIDResponse:
    properties:
      code:
        type: string
      message:
        type: string
      user:
        $ref: '#/definitions/responses.UserResponse'
    type: object
  responses.UserResponse:
    properties:
      createdAt:
        type: string
      email:
        type: string
      firstName:
        type: string
      id:
        type: integer
      lastName:
        type: string
      permissions:
        items:
          type: string
        type: array
      roleId:
        description: Role
        type: integer
      roleName:
        type: string
      updatedAt:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/auth/encrypt-password:
    post:
      consumes:
      - application/json
      description: Encrypt password
      parameters:
      - description: password
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http_response.OkResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http_response.OkResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http_response.OkResponse'
      summary: Encrypt password
      tags:
      - Auth Module (Version 1)
  /api/v1/auth/forgot-password:
    post:
      consumes:
      - application/json
      description: Request to forgot password
      parameters:
      - description: email
        in: body
        name: email
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http_response.OkResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http_response.OkResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http_response.OkResponse'
      summary: Forgot password
      tags:
      - Auth Module (Version 1)
  /api/v1/auth/profile:
    get:
      consumes:
      - application/json
      description: Get profile
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.GetProfileResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http_response.OkResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/http_response.OkResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http_response.OkResponse'
      summary: Get profile
      tags:
      - Auth Module (Version 1)
  /api/v1/auth/reset-password:
    post:
      consumes:
      - application/json
      description: Request to reset password
      parameters:
      - description: email
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: resetPasswordToken
        in: body
        name: resetPasswordToken
        required: true
        schema:
          type: string
      - description: password
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: confirmPassword
        in: body
        name: confirmPassword
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http_response.OkResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http_response.OkResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http_response.OkResponse'
      summary: reset password
      tags:
      - Auth Module (Version 1)
  /api/v1/auth/signin:
    post:
      consumes:
      - application/json
      description: Sign in
      parameters:
      - description: username
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: password
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http_response.OkResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http_response.OkResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http_response.OkResponse'
      summary: Sign in
      tags:
      - Auth Module (Version 1)
  /api/v1/users:
    get:
      consumes:
      - application/json
      description: get users
      parameters:
      - description: page number
        in: query
        name: page
        type: string
      - description: page size
        in: query
        name: limit
        type: string
      - description: page size
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/paginator.Pagination'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/exception.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/exception.ErrorResponse'
      summary: List users
      tags:
      - User Module (Version 1)
    post:
      consumes:
      - application/json
      description: Create an new user
      parameters:
      - description: user first name
        in: body
        name: firstName
        required: true
        schema:
          type: string
      - description: user last name
        in: body
        name: lastName
        required: true
        schema:
          type: string
      - description: user email
        in: body
        name: email
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http_response.OkResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/exception.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/exception.ErrorResponse'
      summary: Create user
      tags:
      - User Module (Version 1)
  /api/v1/users/{user_id}:
    delete:
      consumes:
      - application/json
      description: Delete user
      parameters:
      - description: user id
        in: path
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http_response.OkResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/exception.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/exception.ErrorResponse'
      summary: Delete user
      tags:
      - User Module (Version 1)
    get:
      consumes:
      - application/json
      description: Get user
      parameters:
      - description: user id
        in: path
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.GetUserByIDResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/exception.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/exception.ErrorResponse'
      summary: Get user
      tags:
      - User Module (Version 1)
    put:
      consumes:
      - application/json
      description: Update an existing user
      parameters:
      - description: user id
        in: path
        name: user_id
        required: true
        type: integer
      - description: user first name
        in: body
        name: firstName
        required: true
        schema:
          type: string
      - description: user last name
        in: body
        name: lastName
        required: true
        schema:
          type: string
      - description: user email
        in: body
        name: email
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http_response.OkResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/exception.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/exception.ErrorResponse'
      summary: Update user
      tags:
      - User Module (Version 1)
  /health:
    get:
      description: check the API status
      produces:
      - text/html
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Healthcheck
      tags:
      - Healthcheck
swagger: "2.0"
